# Generated by Django 5.2.4 on 2025-08-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
